print_version expects no arguments, so give it none
Fixes Solaris Studio compiler warning:
"xinput.c", line 357: warning: argument mismatch: 1 arg passed, 0 expected

gcc ignored it because the function declaration didn't specify arguments.
Once you specify (void) for the arguments, gcc then throws up:
xinput.c: In function ‘main’:
xinput.c:357:9: error: too many arguments to function ‘print_version’
xinput.c:147:1: note: declared here

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>